name: Terraria Server Scout

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker Image to scan'
        required: true
        default: 'hexlo/terraria-tmodloader-server'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ github.event.inputs.docker_image }}
          #only-severities: critical,high # only show critical and high CVEs
          #only-fixed: true # filter to fixed CVEs
          exit-code: false  # fail or not based on CVEs found?
          # sarif-file: sca_scout.sarif
          # output: sbom_scout.spdx.json
          # format: spdx
